name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
       
    - name: Prepare WordPress Zip
      run: |
        WP_LINK=$(cat wp-version-control.cfg)
        wget -O "./wordpress.zip" $WP_LINK

    - name: Prepare plugins and theme zip
      run: zip -r wpcontent.zip plugins mu-plugins themes

    - name: Copy Zips to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "./wordpress.zip, ./wpcontent.zip"
        target: ${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}

    - name: Enable Maintenance Mode
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: ".maintenance"
        target: ${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}

    - name: Update Wordpress Core
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          find "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
          rm -r "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-admin/" "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-includes/"
          unzip -o "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wordpress.zip" -d "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/"
          mv "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wordpress/*" "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/
          rm -r "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wordpress"

    - name: Update Plugins and Theme
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rm -rf "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-content/plugins" "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-content/themes"
          unzip "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wp-content/"

    - name: Disable Maintenance Mode and Remove zips
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rm -rf "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/.maintenance"
          rm -rf "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wpcontent.zip"
          rm -rf "${{ github.event_name == 'push' && 'public_html/dev.development-vse-avto.ru' || 'public_html/live.development-vse-avto.ru' }}/wordpress.zip"